version: '3.8'
services:
  # api:
  #   container_name: dolphin-admin-nest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - mongodb
  #     - redis
  #   command: bash -c "npm run prisma:migrate:dev"

  postgres:
    container_name: dolphin-admin-postgres
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  mongodb:
    container_name: dolphin-admin-mongo
    image: mongo
    command: [ "mongod", "--auth" ]
    volumes:
      - mongo_data:/data/db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env

  redis:
    container_name: dolphin-admin-redis
    image: redis
    command: [ "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env

volumes:
  postgres_data:
  mongo_data:
  redis_data:
